### ISSUE TITLE
Non-Vue icons disappear

### ISSUE THREAD

**Issue by jsodeman** [FortAwesome/vue-fontawesome#39]
I was trying to use vue-awesome to fix the issue with icons not toggling, but when I added the @fort-awesome/fontawesome lib to my .vue component all of the non-Vue icons on the page disappeared.

**Comment by robmadole** [comment]
@jsodeman this is a confirmed issue. We'll start looking at some fixes soon.

**Comment by Razi91** [comment]
There is called `fontawesome.noAuto()` in `index.js`, it disables automatic icon searching. After commenting that line it works again.

**Comment by robmadole** [comment]
We just released 0.0.23-1 as a pre-release that removes this line as well.

**Comment by Razi91** [comment]
Thanks, now I can merge it to master without forking this library :+1:

**Comment by pkid169** [comment]
I just got the latest of `0.0.23-1` and that line `fontawesome.noAuto()` is still there? (i.e. this issue still persists)

**Comment by pkid169** [comment]
I see @robmadole commit [here](https://github.com/silverbackdan/vue-fontawesome/commit/2cc65a87798fc6cbc3620d16becadaa38f3b0fc8). For anyone who can't wait for this to be officially released (or there might be some other more appropriate fix), you can point your dependency at the above commit, e.g.

`"@fortawesome/vue-fontawesome": "git://github.com/silverbackdan/vue-fontawesome.git#2cc65a87798fc6cbc3620d16becadaa38f3b0fc8",`

**Comment by pkid169** [comment]
Hi @robmadole, should we still proceed with the mentioned fix? I saw your reply on another issue thread and it seems there might be a better way?

**Comment by blak3r** [comment]
Any updates on this?

**Comment by pkid169** [comment]
@blak3r The issue seems to be fixed on the development branch (prerelease of v0.1.0). I'm not sure when that'll be officially released though.

**Comment by dalabarge** [comment]
I can confirm that using:

```
"@fortawesome/fontawesome-svg-core": "^1.2.0-14",
"@fortawesome/free-solid-svg-icons": "^5.1.0-11",
"@fortawesome/vue-fontawesome": "^0.1.0-5",
```

and the following configuration that intermixing of `<i>` and `<font-awesome-icon>` components work just fine:

```
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'
import { fas } from '@fortawesome/fontawesome-free-solid'
import { config, dom, library } from '@fortawesome/fontawesome-svg-core'
library.add(fas)
dom.watch()
Vue.component('font-awesome-icon', FontAwesomeIcon)
```

**Comment by jasonlundien** [comment]
I am closing this issue.  I believe this has been resolved.  If not let us know and we can reopen.
